### ISSUE TITLE
Get gateway server

### ISSUE THREAD

**Issue by davclark** [BIDS/sensor-group#2]
- [x] Get machine?
- [x] Needs to be on a local physical subnet
- [x] ip
- [x] security setup
- [ ] create isolated subnet 
- [ ] might need two Ethernet cards

**Comment by postfalk** [comment]
Maybe we should start with a very modest machine (~ $200) that can run a regularly updated standard operating system (Debian, Ubuntu) fulfilling university requirements before we get into buying more expansive hardware. IST wants to see that the operating system gets security patches in a timely manner otherwise they will block the IP. Happened to us with a machine running Ubuntu 13.10 two months beyond support cycle.
